const BLOCKS = {
    RETA: "RETA",
    CURVA: "CURVA",
    CONFRONTO: "CONFRONTO",
};

const CHARACTERS = [
    { NOME: "Mario", ICONE: "🔴", VELOCIDADE: 4, MANOBRABILIDADE: 3, PODER: 3 },
    { NOME: "Luigi", ICONE: "🟢", VELOCIDADE: 3, MANOBRABILIDADE: 4, PODER: 4 },
    { NOME: "Peach", ICONE: "🍑", VELOCIDADE: 3, MANOBRABILIDADE: 4, PODER: 2 },
    { NOME: "Toad", ICONE: "🍄", VELOCIDADE: 5, MANOBRABILIDADE: 3, PODER: 1 },
    { NOME: "Yoshi", ICONE: "🦖", VELOCIDADE: 2, MANOBRABILIDADE: 4, PODER: 3 },
    { NOME: "Bowser", ICONE: "🐢", VELOCIDADE: 5, MANOBRABILIDADE: 2, PODER: 5 },
    { NOME: "Donkey Kong", ICONE: "🦍", VELOCIDADE: 2, MANOBRABILIDADE: 2, PODER: 5 },
];

const DICE_SIDES = 6;
const ROUND_OPTIONS = [5, 9, 13];

const ROUND_PAUSE_MS = 900;
const DICE_ANIMATION_FRAMES = 8;
const DICE_ANIMATION_FRAME_MS = 180;
const COUNTDOWN_STEPS = ["3...", "2...", "1...", "Largada! 🏁"];
const COUNTDOWN_STEP_MS = 700;

module.exports = {
    BLOCKS,
    CHARACTERS,
    DICE_SIDES,
    ROUND_OPTIONS,
    ROUND_PAUSE_MS,
    DICE_ANIMATION_FRAMES,
    DICE_ANIMATION_FRAME_MS,
    COUNTDOWN_STEPS,
    COUNTDOWN_STEP_MS,
};
